language: bash

sudo: required

branches:
  only:
    - staging

services:
  -docker

before_script:
  - bash merge_script.sh
after_success:
  - bash pushing_script.sh
  - bash docker_build.sh
  - bash docker_push.sh