language: java

os: linux
dist: trusty
jdk: oraclejdk8

install: true
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"

sudo: required

branches:
  only:
    - staging

services:
  -docker

before_script:
  - bash merge_script.sh

script:
#  - gradle check
  - gradlew check


after_success:
  - bash pushing_script.sh
  - bash docker_build.sh
  - bash docker_push.sh