language: java

os: linux
dist: trusty
jdk: oraclejdk8

sudo: required

branches:
  only:
    - staging

services:
  -docker

before_script:
  - bash merge_script.sh

script:
  - gradle wrapper
  - ./gradlew build --scan -s


after_success:
  - bash pushing_script.sh
  - bash docker_build.sh
  - bash docker_push.sh